# Part 3: GAPMAP Extensions (Notebook)

This notebook is the **Part 3 continuation of Part 2**.

- **Part 2 (baseline) = explicit gaps**: extract sentences where authors *explicitly state* a knowledge gap (e.g., “remains unclear…”) and evaluate against a manual gold standard with ROUGE-L.
- **Part 3 (extensions) = improve the Part 2 evaluation and add implicit gaps**:
  - **Explicit-focused extensions** (not “redoing Part 2,” but making evaluation fairer and analysis stronger):
    - `clean-gold`: remove citation-like junk from explicit gold sentences
    - `semantic-compare`: credit paraphrases (ROUGE can miss correct paraphrases)
    - `export-agreement`: find chunks where multiple models agree (high-confidence candidates)
  - **Implicit-gap capability (GAPMAP’s harder contribution)**: infer **implicit** knowledge gaps that are not stated directly.

## What you run in this notebook

- **Gold hygiene:** `clean-gold`
- **Semantic-augmented eval:** `semantic-compare`
- **Triple-model agreement:** `export-agreement`
- **Implicit-gap scaffolding (for human labeling if you want an implicit gold set):** `implicit-template`, `implicit-sample`
- **TABI batch (GAPMAP-style implicit gaps):** `tabi-extract` → structured **Claim / Grounds / Warrant / Bucket** per chunk
- **Entailment validation (quality screen, not a human gold standard):** `tabi-validate` → `mnli_entailment_prob` / `mnli_entailment_pass`
- **High-confidence export:** `tabi-high-confidence` → calibrated implicit gaps using MNLI threshold + bucket
- **View results:** Section **6b** loads `tabi_outputs*.csv` and shows tables in the notebook.

**Important:** Set `OPENAI_API_KEY` in the next cell *before* TABI or implicit-extract. Terminal runs do **not** see keys you only typed in another notebook unless you export them in that shell.

## 1. API keys and project root

Uncomment and paste your key, or rely on `OPENAI_API_KEY` already set in the kernel environment.

In [ ]:
import os
from pathlib import Path

# --- API key loading (do NOT paste your key into this notebook) ---
# Set OPENAI_API_KEY in your shell before launching Jupyter, e.g.
#   export OPENAI_API_KEY="sk-..."
# Or put it in a local .env file (which is .gitignored).
os.environ.setdefault("OPENAI_MODEL", "gpt-4o")

k = os.environ.get("OPENAI_API_KEY", "").strip()
print("OPENAI_API_KEY present:", bool(k and k.startswith("sk-")), "| len:", len(k))
print("OPENAI_MODEL:", os.environ.get("OPENAI_MODEL", "(default gpt-4o-mini in scripts)"))

PROJECT_ROOT = Path.cwd().resolve()
assert (PROJECT_ROOT / "run_part3.py").exists(), "Start Jupyter from the project folder (contains run_part3.py)"
assert (PROJECT_ROOT / "Dataset").exists() or os.environ.get("GAPMAP_DATASET"), "Need Dataset/ or set GAPMAP_DATASET to your PDF folder"
print("PROJECT_ROOT:", PROJECT_ROOT)

## 2. Helper: run `run_part3.py` from the project root

Uses `.venv/bin/python` if present; otherwise `python` on your PATH.

In [2]:
import subprocess
import sys

VENV_PY = PROJECT_ROOT / ".venv" / "bin" / "python"
PYTHON = str(VENV_PY) if VENV_PY.exists() else sys.executable


def run_part3(*args: str) -> int:
    """Invoke run_part3.py with subcommand + flags. Inherits os.environ (API keys)."""
    cmd = [PYTHON, str(PROJECT_ROOT / "run_part3.py"), *args]
    print("$", " ".join(cmd))
    p = subprocess.run(cmd, cwd=str(PROJECT_ROOT), env=os.environ.copy())
    return p.returncode


print("Using interpreter:", PYTHON)

Using interpreter: /Users/momoba/Desktop/Advanced ML Project /.venv/bin/python

## 3. Gold cleaning, semantic compare, agreement export

In [3]:
run_part3("clean-gold")

$ /Users/momoba/Desktop/Advanced ML Project /.venv/bin/python /Users/momoba/Desktop/Advanced ML Project /run_part3.py clean-gold

Wrote /Users/momoba/Desktop/Advanced ML Project /Part3_Output/gold_standard_cleaned.csv
Chunks with ≥1 gap after clean: 93 (citation-like sentences dropped: 7)

0

In [4]:
run_part3("semantic-compare", "--threshold", "0.55")

$ /Users/momoba/Desktop/Advanced ML Project /.venv/bin/python /Users/momoba/Desktop/Advanced ML Project /run_part3.py semantic-compare --threshold 0.55

=== Semantic-augmented match: max(ROUGE-L, bow-cosine) >= 0.55 ===
Model                      Precision     Recall         F1
---------------------------------------------------------
gpt4o_mini                    0.5870     0.9213     0.7171
gpt_4o                        0.8839     0.9167     0.9000
ollama                        0.5351     0.8939     0.6695

Saved to /Users/momoba/Desktop/Advanced ML Project /Part3_Output/semantic_compare.txt
Note: This credits some paraphrases ROUGE alone would miss; compare to `python run_part2.py --compare`.

0

In [5]:
run_part3("export-agreement")

$ /Users/momoba/Desktop/Advanced ML Project /.venv/bin/python /Users/momoba/Desktop/Advanced ML Project /run_part3.py export-agreement

Chunks with gaps in all three models: 99
Wrote /Users/momoba/Desktop/Advanced ML Project /Part3_Output/high_confidence_chunks.csv

0

## 4. Implicit-gap scaffolding (templates + optional one-chunk demo)

In [6]:
run_part3("implicit-template", "--n", "50")

$ /Users/momoba/Desktop/Advanced ML Project /.venv/bin/python /Users/momoba/Desktop/Advanced ML Project /run_part3.py implicit-template --n 50

Wrote /Users/momoba/Desktop/Advanced ML Project /Part3_Output/implicit_gold_template.csv (50 rows). Fill implicit_gap_sentence manually.

0

In [7]:
run_part3("implicit-sample", "--n", "50")

$ /Users/momoba/Desktop/Advanced ML Project /.venv/bin/python /Users/momoba/Desktop/Advanced ML Project /run_part3.py implicit-sample --n 50

Wrote /Users/momoba/Desktop/Advanced ML Project /Part3_Output/implicit_annotation_sample.csv (50 rows).

0

In [8]:
# Optional: paid API — one chunk implicit gap (set chunk_id)
CHUNK_ID = 21
if os.environ.get("OPENAI_API_KEY", "").strip().startswith("sk-"):
    run_part3("implicit-extract", "--chunk-id", str(CHUNK_ID))
else:
    print("Skip: set OPENAI_API_KEY in cell 1")

$ /Users/momoba/Desktop/Advanced ML Project /.venv/bin/python /Users/momoba/Desktop/Advanced ML Project /run_part3.py implicit-extract --chunk-id 21

chunk_id=21
The study does not address whether the observed post-merger performance recovery would persist or change with even longer post-merger periods beyond the twenty rounds tested.

## 5. TABI batch (Claim / Grounds / Warrant / Bucket)

1. **`--dry-run`** — no API; writes schema sample (fast path check).
2. **Small live test** — `--max-chunks 10` after a valid key.
3. **Full corpus** — remove `--max-chunks`; add `--resume` if restarting.

Pre-flight auth is built into `run_part3.py`; bad keys stop before the full loop.

In [9]:
# No API — verify paths and CSV columns (~1 min: loads all PDFs)
run_part3(
    "tabi-extract",
    "--dry-run",
    "--max-chunks",
    "5",
    "--out",
    "Part3_Output/tabi_outputs_notebook_dryrun.csv",
)

$ /Users/momoba/Desktop/Advanced ML Project /.venv/bin/python /Users/momoba/Desktop/Advanced ML Project /run_part3.py tabi-extract --dry-run --max-chunks 5 --out Part3_Output/tabi_outputs_notebook_dryrun.csv

DRY-RUN mode: no API calls; writing placeholder TABI JSON per chunk.
Wrote 5 new inference rows → Part3_Output/tabi_outputs_notebook_dryrun.csv (file now has 5 rows, one per chunk_id).

TABI (openai/dry-run (dry-run)):   0%|          | 0/5 [00:00<?, ?it/s]
TABI (openai/dry-run (dry-run)): 100%|██████████| 5/5 [00:00<00:00, 34044.68it/s]

0

In [10]:
# Live test (requires real OPENAI_API_KEY in this kernel)
if os.environ.get("OPENAI_API_KEY", "").strip().startswith("sk-"):
    os.environ.setdefault("OPENAI_MODEL", "gpt-4o")
    run_part3(
        "tabi-extract",
        "--backend",
        "openai",
        "--max-chunks",
        "10",
        "--out",
        "Part3_Output/tabi_outputs_notebook_test.csv",
        "--sleep",
        "0.25",
    )
else:
    print("Skip: set OPENAI_API_KEY in cell 1")

$ /Users/momoba/Desktop/Advanced ML Project /.venv/bin/python /Users/momoba/Desktop/Advanced ML Project /run_part3.py tabi-extract --backend openai --max-chunks 10 --out Part3_Output/tabi_outputs_notebook_test.csv --sleep 0.25

OpenAI pre-flight OK (gpt-4o).

TABI (openai/gpt-4o):   0%|          | 0/10 [00:00<?, ?it/s]

TABI (openai/gpt-4o):  10%|█         | 1/10 [00:01<00:12,  1.36s/it]

TABI (openai/gpt-4o):  20%|██        | 2/10 [00:03<00:16,  2.07s/it]

TABI (openai/gpt-4o):  30%|███       | 3/10 [00:05<00:14,  2.06s/it]

TABI (openai/gpt-4o):  40%|████      | 4/10 [00:07<00:11,  1.98s/it]

TABI (openai/gpt-4o):  50%|█████     | 5/10 [00:09<00:09,  1.84s/it]

TABI (openai/gpt-4o):  60%|██████    | 6/10 [00:11<00:08,  2.00s/it]

TABI (openai/gpt-4o):  70%|███████   | 7/10 [00:13<00:06,  2.00s/it]

TABI (openai/gpt-4o):  80%|████████  | 8/10 [00:16<00:04,  2.15s/it]

TABI (openai/gpt-4o):  90%|█████████ | 9/10 [00:18<00:02,  2.05s/it]

Wrote 10 new inference rows → Part3_Output/tabi_outputs_notebook_test.csv (file now has 10 rows, one per chunk_id).

TABI (openai/gpt-4o): 100%|██████████| 10/10 [00:19<00:00,  1.86s/it]
TABI (openai/gpt-4o): 100%|██████████| 10/10 [00:19<00:00,  1.95s/it]

In [11]:
import pandas as pd
from IPython.display import display

p = PROJECT_ROOT / "Part3_Output" / "tabi_outputs_notebook_test.csv"
if not p.exists():
    p = PROJECT_ROOT / "Part3_Output" / "tabi_outputs.csv"
if p.exists():
    d = pd.read_csv(p)
    c = d["claim"].fillna("").astype(str).str.strip()
    good = ((c != "") & (c.str.upper() != "NONE")).sum()
    err = d["parse_error"].fillna("").astype(str).str.len().gt(0).sum()
    print("File:", p.name)
    print("non-empty claims (not NONE):", int(good))
    print("rows with parse_error text:", int(err))
    display(d.head(3))
else:
    print("No TABI CSV found yet — run the cells above.")

File: tabi_outputs_notebook_test.csv
non-empty claims (not NONE): 10
rows with parse_error text: 0

,chunk_id,article_filename,word_count,backend,model,claim,grounds,warrant,bucket,parse_error,raw_response_excerpt
0,0,Does-college-education-make-women-less-likely-...,971,openai,gpt-4o,The causal mechanisms by which higher educatio...,the extent to which this reflects a causal eff...,The text acknowledges challenges in establishi...,more_probable,NaN,"{""claim"":""The causal mechanisms by which highe..."
1,1,Does-college-education-make-women-less-likely-...,976,openai,gpt-4o,The impact of higher education expansion on ma...,this finding might not generalise to rural ori...,The text suggests that the positive effects ob...,more_probable,NaN,"{""claim"":""The impact of higher education expan..."
2,2,Does-college-education-make-women-less-likely-...,989,openai,gpt-4o,The impact of the hukou system on educational ...,The hukou (household registration) system...is...,While the text discusses educational assortati...,more_probable,NaN,"{""claim"":""The impact of the hukou system on ed..."

## 6. Optional: RoBERTa-MNLI entailment (`tabi-validate`)

Requires: `pip install torch transformers` (see `requirements_part3_optional.txt`).

In [12]:
TAB_IN = PROJECT_ROOT / "Part3_Output" / "tabi_outputs.csv"
if TAB_IN.exists():
    try:
        import torch  # noqa: F401
        import transformers  # noqa: F401
    except ImportError:
        print("Install: pip install torch transformers")
    else:
        run_part3("tabi-validate", "--input", str(TAB_IN), "--threshold", "0.4")
else:
    print("Missing", TAB_IN, "— run full tabi-extract first.")

$ /Users/momoba/Desktop/Advanced ML Project /.venv/bin/python /Users/momoba/Desktop/Advanced ML Project /run_part3.py tabi-validate --input /Users/momoba/Desktop/Advanced ML Project /Part3_Output/tabi_outputs.csv --threshold 0.4

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

Loading weights:   0%|          | 0/393 [00:00<?, ?it/s]
Loading weights: 100%|██████████| 393/393 [00:00<00:00, 7765.29it/s]
[transformers] RobertaForSequenceClassification LOAD REPORT from: roberta-large-mnli
Key                         | Status     |  |
----------------------------+------------+--+-
roberta.pooler.dense.weight | UNEXPECTED |  |
roberta.pooler.dense.bias   | UNEXPECTED |  |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.

MNLI entailment:   0%|          | 0/1367 [00:00<?, ?it/s]

MNLI entailment:   0%|          | 1/1367 [00:01<42:42,  1.88s/it]
MNLI entailment:   0%|          | 3/1367 [00:02<12:12,  1.86it/s]

MNLI entailment:   0%|          | 5/1367 [00:02<06:38,  3.41it/s]
MNLI entailment:   1%|          | 7/1367 [00:02<04:26,  5.10it/s]

MNLI entailment:   1%|          | 9/1367 [00:02<03:21,  6.74it/s]
MNLI entailment:   1%|          | 11/1367 [00:02<02:42,  8.35it/s]

MNLI entailment:   1%|          | 13/1367 [00:02<02:19,  9.67it/s]
MNLI entailment:   1%|          | 15/1367 [00:02<02:04, 10.89it/s]

MNLI entailment:   1%|          | 17/1367 [00:02<01:53, 11.86it/s]
MNLI entailment:   1%|▏         | 19/1367 [00:03<01:46, 12.71it/s]

MNLI entailment:   2%|▏         | 21/1367 [00:03<01:39, 13.48it/s]
MNLI entailment:   2%|▏         | 23/1367 [00:03<01:35, 14.04it/s]

MNLI entailment:   2%|▏         | 25/1367 [00:03<01:36, 13.92it/s]
MNLI entailment:   2%|▏         | 27/1367 [00:03<01:33, 14.29it/s]

MNLI entailment:   2%|▏         | 29/1367 [00:03<01:31, 14.66it/s]
MNLI entailment:   2%|▏         | 31/1367 [00:03<01:29, 14.98it/s]

MNLI entailment:   2%|▏         | 33/1367 [00:03<01:24, 15.80it/s]
MNLI entailment:   3%|▎         | 35/1367 [00:04<01:24, 15.71it/s]

MNLI entailment:   3%|▎         | 37/1367 [00:04<01:26, 15.34it/s]
MNLI entailment:   3%|▎         | 39/1367 [00:04<01:24, 15.63it/s]

MNLI entailment:   3%|▎         | 41/1367 [00:04<01:25, 15.48it/s]
MNLI entailment:   3%|▎         | 43/1367 [00:04<01:26, 15.38it/s]

MNLI entailment:   3%|▎         | 45/1367 [00:04<01:27, 15.03it/s]
MNLI entailment:   3%|▎         | 47/1367 [00:04<01:26, 15.22it/s]

MNLI entailment:   4%|▎         | 49/1367 [00:05<01:25, 15.36it/s]
MNLI entailment:   4%|▎         | 51/1367 [00:05<01:26, 15.18it/s]

MNLI entailment:   4%|▍         | 53/1367 [00:05<01:25, 15.44it/s]
MNLI entailment:   4%|▍         | 55/1367 [00:05<01:24, 15.52it/s]

MNLI entailment:   4%|▍         | 57/1367 [00:05<01:23, 15.66it/s]
MNLI entailment:   4%|▍         | 59/1367 [00:05<01:25, 15.34it/s]

MNLI entailment:   4%|▍         | 61/1367 [00:05<01:27, 14.91it/s]
MNLI entailment:   5%|▍         | 63/1367 [00:05<01:28, 14.80it/s]

MNLI entailment:   5%|▍         | 65/1367 [00:06<01:29, 14.51it/s]
MNLI entailment:   5%|▍         | 67/1367 [00:06<01:30, 14.40it/s]

MNLI entailment:   5%|▌         | 69/1367 [00:06<01:28, 14.65it/s]
MNLI entailment:   5%|▌         | 71/1367 [00:06<01:25, 15.22it/s]

MNLI entailment:   5%|▌         | 73/1367 [00:06<01:24, 15.34it/s]
MNLI entailment:   5%|▌         | 75/1367 [00:06<01:22, 15.67it/s]

MNLI entailment:   6%|▌         | 77/1367 [00:06<01:22, 15.72it/s]
MNLI entailment:   6%|▌         | 79/1367 [00:07<01:23, 15.36it/s]

MNLI entailment:   6%|▌         | 81/1367 [00:07<01:22, 15.58it/s]
MNLI entailment:   6%|▌         | 83/1367 [00:07<01:21, 15.70it/s]

MNLI entailment:   6%|▌         | 85/1367 [00:07<01:20, 15.85it/s]
MNLI entailment:   6%|▋         | 87/1367 [00:07<01:19, 16.11it/s]

MNLI entailment:   7%|▋         | 89/1367 [00:07<01:18, 16.37it/s]
MNLI entailment:   7%|▋         | 91/1367 [00:07<01:18, 16.24it/s]

MNLI entailment:   7%|▋         | 93/1367 [00:07<01:18, 16.27it/s]
MNLI entailment:   7%|▋         | 95/1367 [00:08<01:20, 15.77it/s]

MNLI entailment:   7%|▋         | 97/1367 [00:08<01:20, 15.69it/s]
MNLI entailment:   7%|▋         | 99/1367 [00:08<01:19, 15.89it/s]

MNLI entailment:   7%|▋         | 101/1367 [00:08<01:21, 15.62it/s]
MNLI entailment:   8%|▊         | 103/1367 [00:08<01:19, 15.82it/s]

MNLI entailment:   8%|▊         | 105/1367 [00:08<01:15, 16.67it/s]
MNLI entailment:   8%|▊         | 107/1367 [00:08<01:15, 16.60it/s]

MNLI entailment:   8%|▊         | 109/1367 [00:08<01:16, 16.46it/s]
MNLI entailment:   8%|▊         | 111/1367 [00:08<01:17, 16.24it/s]

MNLI entailment:   8%|▊         | 113/1367 [00:09<01:17, 16.20it/s]
MNLI entailment:   8%|▊         | 115/1367 [00:09<01:17, 16.20it/s]

MNLI entailment:   9%|▊         | 117/1367 [00:09<01:15, 16.55it/s]
MNLI entailment:   9%|▊         | 119/1367 [00:09<01:17, 16.10it/s]

MNLI entailment:   9%|▉         | 121/1367 [00:09<01:18, 15.90it/s]
MNLI entailment:   9%|▉         | 123/1367 [00:09<01:19, 15.69it/s]

MNLI entailment:   9%|▉         | 125/1367 [00:09<01:21, 15.33it/s]
MNLI entailment:   9%|▉         | 127/1367 [00:09<01:17, 15.90it/s]

MNLI entailment:   9%|▉         | 129/1367 [00:10<01:18, 15.73it/s]
MNLI entailment:  10%|▉         | 131/1367 [00:10<01:17, 15.89it/s]

MNLI entailment:  10%|▉         | 133/1367 [00:10<01:15, 16.34it/s]
MNLI entailment:  10%|▉         | 135/1367 [00:10<01:15, 16.35it/s]

MNLI entailment:  10%|█         | 137/1367 [00:10<01:13, 16.72it/s]
MNLI entailment:  10%|█         | 139/1367 [00:10<01:12, 17.02it/s]

MNLI entailment:  10%|█         | 141/1367 [00:10<01:13, 16.75it/s]
MNLI entailment:  10%|█         | 143/1367 [00:10<01:12, 16.91it/s]

MNLI entailment:  11%|█         | 146/1367 [00:11<01:04, 18.98it/s]
MNLI entailment:  11%|█         | 148/1367 [00:11<01:08, 17.80it/s]

MNLI entailment:  11%|█         | 150/1367 [00:11<01:10, 17.30it/s]
MNLI entailment:  11%|█         | 152/1367 [00:11<01:11, 16.94it/s]

MNLI entailment:  11%|█▏        | 154/1367 [00:11<01:12, 16.64it/s]
MNLI entailment:  11%|█▏        | 156/1367 [00:11<01:13, 16.44it/s]

MNLI entailment:  12%|█▏        | 158/1367 [00:11<01:14, 16.18it/s]
MNLI entailment:  12%|█▏        | 160/1367 [00:11<01:15, 16.08it/s]

MNLI entailment:  12%|█▏        | 162/1367 [00:12<01:15, 15.88it/s]
MNLI entailment:  12%|█▏        | 164/1367 [00:12<01:15, 15.86it/s]

MNLI entailment:  12%|█▏        | 166/1367 [00:12<01:17, 15.58it/s]
MNLI entailment:  12%|█▏        | 168/1367 [00:12<01:16, 15.73it/s]

MNLI entailment:  12%|█▏        | 170/1367 [00:12<01:14, 16.11it/s]
MNLI entailment:  13%|█▎        | 172/1367 [00:12<01:16, 15.60it/s]

MNLI entailment:  13%|█▎        | 174/1367 [00:12<01:16, 15.60it/s]
MNLI entailment:  13%|█▎        | 176/1367 [00:12<01:14, 15.92it/s]

MNLI entailment:  13%|█▎        | 178/1367 [00:13<01:15, 15.65it/s]
MNLI entailment:  13%|█▎        | 180/1367 [00:13<01:16, 15.44it/s]

MNLI entailment:  13%|█▎        | 182/1367 [00:13<01:17, 15.33it/s]
MNLI entailment:  13%|█▎        | 184/1367 [00:13<01:16, 15.47it/s]

MNLI entailment:  14%|█▎        | 186/1367 [00:13<01:14, 15.94it/s]
MNLI entailment:  14%|█▍        | 188/1367 [00:13<01:15, 15.57it/s]

MNLI entailment:  14%|█▍        | 190/1367 [00:13<01:17, 15.17it/s]
MNLI entailment:  14%|█▍        | 192/1367 [00:14<01:16, 15.41it/s]

MNLI entailment:  14%|█▍        | 194/1367 [00:14<01:15, 15.59it/s]
MNLI entailment:  14%|█▍        | 196/1367 [00:14<01:12, 16.09it/s]

MNLI entailment:  14%|█▍        | 198/1367 [00:14<01:12, 16.04it/s]
MNLI entailment:  15%|█▍        | 200/1367 [00:14<01:13, 15.91it/s]

MNLI entailment:  15%|█▍        | 202/1367 [00:14<01:15, 15.40it/s]
MNLI entailment:  15%|█▍        | 204/1367 [00:14<01:17, 14.96it/s]

MNLI entailment:  15%|█▌        | 206/1367 [00:14<01:17, 15.01it/s]
MNLI entailment:  15%|█▌        | 208/1367 [00:15<01:16, 15.18it/s]

MNLI entailment:  15%|█▌        | 210/1367 [00:15<01:13, 15.78it/s]
MNLI entailment:  16%|█▌        | 212/1367 [00:15<01:11, 16.19it/s]

MNLI entailment:  16%|█▌        | 214/1367 [00:15<01:11, 16.13it/s]
MNLI entailment:  16%|█▌        | 216/1367 [00:15<01:10, 16.41it/s]

MNLI entailment:  16%|█▌        | 218/1367 [00:15<01:11, 16.02it/s]
MNLI entailment:  16%|█▌        | 220/1367 [00:15<01:11, 16.05it/s]

MNLI entailment:  16%|█▌        | 222/1367 [00:15<01:11, 15.91it/s]
MNLI entailment:  16%|█▋        | 224/1367 [00:16<01:11, 15.90it/s]

MNLI entailment:  17%|█▋        | 226/1367 [00:16<01:11, 15.94it/s]
MNLI entailment:  17%|█▋        | 228/1367 [00:16<01:11, 15.91it/s]

MNLI entailment:  17%|█▋        | 230/1367 [00:16<01:12, 15.66it/s]
MNLI entailment:  17%|█▋        | 232/1367 [00:16<01:13, 15.53it/s]

MNLI entailment:  17%|█▋        | 234/1367 [00:16<01:12, 15.58it/s]
MNLI entailment:  17%|█▋        | 236/1367 [00:16<01:11, 15.71it/s]

MNLI entailment:  17%|█▋        | 238/1367 [00:16<01:13, 15.36it/s]
MNLI entailment:  18%|█▊        | 240/1367 [00:17<01:11, 15.80it/s]

MNLI entailment:  18%|█▊        | 242/1367 [00:17<01:11, 15.73it/s]
MNLI entailment:  18%|█▊        | 244/1367 [00:17<01:12, 15.58it/s]

MNLI entailment:  18%|█▊        | 246/1367 [00:17<01:12, 15.38it/s]
MNLI entailment:  18%|█▊        | 248/1367 [00:17<01:16, 14.54it/s]

MNLI entailment:  18%|█▊        | 250/1367 [00:17<01:32, 12.01it/s]
MNLI entailment:  18%|█▊        | 252/1367 [00:17<01:27, 12.69it/s]

MNLI entailment:  19%|█▊        | 254/1367 [00:18<01:23, 13.39it/s]
MNLI entailment:  19%|█▊        | 256/1367 [00:18<01:20, 13.84it/s]

MNLI entailment:  19%|█▉        | 258/1367 [00:18<01:16, 14.56it/s]
MNLI entailment:  19%|█▉        | 260/1367 [00:18<01:14, 14.89it/s]

MNLI entailment:  19%|█▉        | 262/1367 [00:18<01:14, 14.85it/s]
MNLI entailment:  19%|█▉        | 264/1367 [00:18<01:11, 15.38it/s]

MNLI entailment:  19%|█▉        | 266/1367 [00:18<01:09, 15.85it/s]
MNLI entailment:  20%|█▉        | 268/1367 [00:18<01:08, 15.93it/s]

MNLI entailment:  20%|█▉        | 270/1367 [00:19<01:07, 16.19it/s]
MNLI entailment:  20%|█▉        | 272/1367 [00:19<01:05, 16.75it/s]

MNLI entailment:  20%|██        | 274/1367 [00:19<01:06, 16.43it/s]
MNLI entailment:  20%|██        | 276/1367 [00:19<01:04, 16.86it/s]

MNLI entailment:  20%|██        | 278/1367 [00:19<01:05, 16.58it/s]
MNLI entailment:  20%|██        | 280/1367 [00:19<01:06, 16.39it/s]

MNLI entailment:  21%|██        | 282/1367 [00:19<01:07, 16.15it/s]
MNLI entailment:  21%|██        | 284/1367 [00:19<01:07, 16.00it/s]

MNLI entailment:  21%|██        | 286/1367 [00:20<01:06, 16.29it/s]
MNLI entailment:  21%|██        | 288/1367 [00:20<01:07, 16.05it/s]

MNLI entailment:  21%|██        | 290/1367 [00:20<01:09, 15.49it/s]
MNLI entailment:  21%|██▏       | 292/1367 [00:20<01:12, 14.78it/s]

MNLI entailment:  22%|██▏       | 294/1367 [00:20<01:10, 15.32it/s]
MNLI entailment:  22%|██▏       | 296/1367 [00:20<01:08, 15.74it/s]

MNLI entailment:  22%|██▏       | 298/1367 [00:20<01:07, 15.75it/s]
MNLI entailment:  22%|██▏       | 300/1367 [00:20<01:07, 15.74it/s]

MNLI entailment:  22%|██▏       | 302/1367 [00:21<01:07, 15.74it/s]
MNLI entailment:  22%|██▏       | 304/1367 [00:21<01:06, 15.87it/s]

MNLI entailment:  22%|██▏       | 306/1367 [00:21<01:06, 15.95it/s]
MNLI entailment:  23%|██▎       | 308/1367 [00:21<01:05, 16.07it/s]

MNLI entailment:  23%|██▎       | 310/1367 [00:21<01:05, 16.16it/s]
MNLI entailment:  23%|██▎       | 312/1367 [00:21<01:03, 16.53it/s]

MNLI entailment:  23%|██▎       | 314/1367 [00:21<01:03, 16.51it/s]
MNLI entailment:  23%|██▎       | 316/1367 [00:21<01:04, 16.23it/s]

MNLI entailment:  23%|██▎       | 318/1367 [00:22<01:03, 16.63it/s]
MNLI entailment:  23%|██▎       | 320/1367 [00:22<01:01, 17.08it/s]

MNLI entailment:  24%|██▎       | 322/1367 [00:22<01:00, 17.24it/s]
MNLI entailment:  24%|██▎       | 324/1367 [00:22<01:01, 17.00it/s]

MNLI entailment:  24%|██▍       | 326/1367 [00:22<01:02, 16.57it/s]
MNLI entailment:  24%|██▍       | 328/1367 [00:22<01:02, 16.60it/s]

MNLI entailment:  24%|██▍       | 330/1367 [00:22<01:02, 16.58it/s]
MNLI entailment:  24%|██▍       | 332/1367 [00:22<01:02, 16.59it/s]

MNLI entailment:  24%|██▍       | 334/1367 [00:23<01:02, 16.52it/s]
MNLI entailment:  25%|██▍       | 336/1367 [00:23<01:02, 16.52it/s]

MNLI entailment:  25%|██▍       | 338/1367 [00:23<01:03, 16.28it/s]
MNLI entailment:  25%|██▍       | 340/1367 [00:23<01:02, 16.40it/s]

MNLI entailment:  25%|██▌       | 342/1367 [00:23<01:02, 16.47it/s]
MNLI entailment:  25%|██▌       | 344/1367 [00:23<01:03, 16.21it/s]

MNLI entailment:  25%|██▌       | 346/1367 [00:23<01:01, 16.67it/s]
MNLI entailment:  25%|██▌       | 348/1367 [00:23<01:01, 16.52it/s]

MNLI entailment:  26%|██▌       | 350/1367 [00:24<01:01, 16.44it/s]
MNLI entailment:  26%|██▌       | 352/1367 [00:24<01:01, 16.42it/s]

MNLI entailment:  26%|██▌       | 354/1367 [00:24<00:59, 17.16it/s]
MNLI entailment:  26%|██▌       | 356/1367 [00:24<00:58, 17.39it/s]

MNLI entailment:  26%|██▌       | 358/1367 [00:24<00:59, 17.06it/s]
MNLI entailment:  26%|██▋       | 360/1367 [00:24<00:59, 16.84it/s]

MNLI entailment:  26%|██▋       | 362/1367 [00:24<00:58, 17.07it/s]
MNLI entailment:  27%|██▋       | 364/1367 [00:24<00:56, 17.70it/s]

MNLI entailment:  27%|██▋       | 366/1367 [00:24<00:57, 17.31it/s]
MNLI entailment:  27%|██▋       | 368/1367 [00:25<00:55, 17.86it/s]

MNLI entailment:  27%|██▋       | 370/1367 [00:25<00:58, 17.10it/s]
MNLI entailment:  27%|██▋       | 372/1367 [00:25<01:00, 16.35it/s]

MNLI entailment:  27%|██▋       | 374/1367 [00:25<01:00, 16.36it/s]
MNLI entailment:  28%|██▊       | 376/1367 [00:25<00:59, 16.52it/s]

MNLI entailment:  28%|██▊       | 378/1367 [00:25<00:58, 16.95it/s]
MNLI entailment:  28%|██▊       | 380/1367 [00:25<00:59, 16.72it/s]

MNLI entailment:  28%|██▊       | 382/1367 [00:25<00:58, 16.86it/s]
MNLI entailment:  28%|██▊       | 384/1367 [00:26<00:58, 16.76it/s]

MNLI entailment:  28%|██▊       | 386/1367 [00:26<00:58, 16.71it/s]
MNLI entailment:  28%|██▊       | 388/1367 [00:26<00:57, 17.06it/s]

MNLI entailment:  29%|██▊       | 390/1367 [00:26<00:56, 17.29it/s]
MNLI entailment:  29%|██▊       | 392/1367 [00:26<00:57, 17.03it/s]

MNLI entailment:  29%|██▉       | 394/1367 [00:26<00:57, 16.88it/s]
MNLI entailment:  29%|██▉       | 396/1367 [00:26<00:57, 16.83it/s]

MNLI entailment:  29%|██▉       | 398/1367 [00:26<00:56, 17.18it/s]
MNLI entailment:  29%|██▉       | 400/1367 [00:26<00:54, 17.76it/s]

MNLI entailment:  29%|██▉       | 402/1367 [00:27<00:54, 17.76it/s]
MNLI entailment:  30%|██▉       | 404/1367 [00:27<00:55, 17.30it/s]

MNLI entailment:  30%|██▉       | 406/1367 [00:27<00:55, 17.41it/s]
MNLI entailment:  30%|██▉       | 408/1367 [00:27<00:54, 17.49it/s]

MNLI entailment:  30%|██▉       | 410/1367 [00:27<00:55, 17.17it/s]
MNLI entailment:  30%|███       | 412/1367 [00:27<00:57, 16.69it/s]

MNLI entailment:  30%|███       | 414/1367 [00:27<00:56, 16.99it/s]
MNLI entailment:  30%|███       | 416/1367 [00:27<00:57, 16.54it/s]

MNLI entailment:  31%|███       | 418/1367 [00:28<00:57, 16.53it/s]
MNLI entailment:  31%|███       | 420/1367 [00:28<00:57, 16.50it/s]

MNLI entailment:  31%|███       | 422/1367 [00:28<00:57, 16.46it/s]
MNLI entailment:  31%|███       | 424/1367 [00:28<00:57, 16.45it/s]

MNLI entailment:  31%|███       | 426/1367 [00:28<00:58, 16.17it/s]
MNLI entailment:  31%|███▏      | 428/1367 [00:28<00:58, 15.99it/s]

MNLI entailment:  31%|███▏      | 430/1367 [00:28<01:00, 15.50it/s]
MNLI entailment:  32%|███▏      | 432/1367 [00:28<00:59, 15.77it/s]

MNLI entailment:  32%|███▏      | 434/1367 [00:29<00:56, 16.55it/s]
MNLI entailment:  32%|███▏      | 436/1367 [00:29<00:56, 16.46it/s]

MNLI entailment:  32%|███▏      | 438/1367 [00:29<00:55, 16.79it/s]
MNLI entailment:  32%|███▏      | 440/1367 [00:29<00:55, 16.70it/s]

MNLI entailment:  32%|███▏      | 442/1367 [00:29<00:55, 16.56it/s]
MNLI entailment:  32%|███▏      | 444/1367 [00:29<00:53, 17.35it/s]

MNLI entailment:  33%|███▎      | 446/1367 [00:29<00:53, 17.14it/s]
MNLI entailment:  33%|███▎      | 448/1367 [00:29<00:55, 16.68it/s]

MNLI entailment:  33%|███▎      | 450/1367 [00:29<00:55, 16.62it/s]
MNLI entailment:  33%|███▎      | 452/1367 [00:30<00:55, 16.36it/s]

MNLI entailment:  33%|███▎      | 454/1367 [00:30<00:55, 16.35it/s]
MNLI entailment:  33%|███▎      | 456/1367 [00:30<00:54, 16.64it/s]

MNLI entailment:  34%|███▎      | 458/1367 [00:30<00:56, 16.09it/s]
MNLI entailment:  34%|███▎      | 460/1367 [00:30<00:57, 15.77it/s]

MNLI entailment:  34%|███▍      | 462/1367 [00:30<00:57, 15.82it/s]
MNLI entailment:  34%|███▍      | 464/1367 [00:30<00:57, 15.70it/s]

MNLI entailment:  34%|███▍      | 466/1367 [00:30<00:56, 15.91it/s]
MNLI entailment:  34%|███▍      | 468/1367 [00:31<00:54, 16.35it/s]

MNLI entailment:  34%|███▍      | 470/1367 [00:31<00:54, 16.32it/s]
MNLI entailment:  35%|███▍      | 472/1367 [00:31<00:54, 16.28it/s]

MNLI entailment:  35%|███▍      | 474/1367 [00:31<00:54, 16.37it/s]
MNLI entailment:  35%|███▍      | 476/1367 [00:31<00:52, 17.11it/s]

MNLI entailment:  35%|███▍      | 478/1367 [00:31<00:52, 16.95it/s]
MNLI entailment:  35%|███▌      | 480/1367 [00:31<00:51, 17.25it/s]

MNLI entailment:  35%|███▌      | 482/1367 [00:31<00:51, 17.06it/s]
MNLI entailment:  35%|███▌      | 484/1367 [00:32<00:51, 17.19it/s]

MNLI entailment:  36%|███▌      | 486/1367 [00:32<00:51, 17.00it/s]
MNLI entailment:  36%|███▌      | 488/1367 [00:32<00:52, 16.61it/s]

MNLI entailment:  36%|███▌      | 490/1367 [00:32<00:51, 16.94it/s]
MNLI entailment:  36%|███▌      | 492/1367 [00:32<00:52, 16.54it/s]

MNLI entailment:  36%|███▌      | 494/1367 [00:32<00:50, 17.27it/s]
MNLI entailment:  36%|███▋      | 496/1367 [00:32<00:51, 17.07it/s]

MNLI entailment:  36%|███▋      | 498/1367 [00:32<00:51, 16.87it/s]
MNLI entailment:  37%|███▋      | 500/1367 [00:32<00:50, 17.14it/s]

MNLI entailment:  37%|███▋      | 502/1367 [00:33<00:49, 17.39it/s]
MNLI entailment:  37%|███▋      | 504/1367 [00:33<00:50, 17.04it/s]

MNLI entailment:  37%|███▋      | 506/1367 [00:33<00:51, 16.77it/s]
MNLI entailment:  37%|███▋      | 508/1367 [00:33<00:51, 16.74it/s]

MNLI entailment:  37%|███▋      | 510/1367 [00:33<00:52, 16.40it/s]
MNLI entailment:  37%|███▋      | 512/1367 [00:33<00:52, 16.17it/s]

MNLI entailment:  38%|███▊      | 514/1367 [00:33<00:52, 16.23it/s]
MNLI entailment:  38%|███▊      | 516/1367 [00:33<00:52, 16.28it/s]

MNLI entailment:  38%|███▊      | 518/1367 [00:34<00:52, 16.27it/s]
MNLI entailment:  38%|███▊      | 520/1367 [00:34<00:51, 16.29it/s]

MNLI entailment:  38%|███▊      | 522/1367 [00:34<00:51, 16.28it/s]
MNLI entailment:  38%|███▊      | 524/1367 [00:34<00:50, 16.76it/s]

MNLI entailment:  38%|███▊      | 526/1367 [00:34<00:51, 16.38it/s]
MNLI entailment:  39%|███▊      | 528/1367 [00:34<00:53, 15.81it/s]

MNLI entailment:  39%|███▉      | 530/1367 [00:34<00:52, 15.96it/s]
MNLI entailment:  39%|███▉      | 532/1367 [00:34<00:50, 16.43it/s]

MNLI entailment:  39%|███▉      | 534/1367 [00:35<00:51, 16.18it/s]
MNLI entailment:  39%|███▉      | 536/1367 [00:35<00:50, 16.58it/s]

MNLI entailment:  39%|███▉      | 538/1367 [00:35<00:49, 16.62it/s]
MNLI entailment:  40%|███▉      | 540/1367 [00:35<00:48, 17.00it/s]

MNLI entailment:  40%|███▉      | 542/1367 [00:35<00:51, 15.90it/s]
MNLI entailment:  40%|███▉      | 544/1367 [00:35<00:52, 15.73it/s]

MNLI entailment:  40%|███▉      | 546/1367 [00:35<00:52, 15.60it/s]
MNLI entailment:  40%|████      | 548/1367 [00:35<00:52, 15.51it/s]

MNLI entailment:  40%|████      | 550/1367 [00:36<00:51, 15.79it/s]
MNLI entailment:  40%|████      | 552/1367 [00:36<00:53, 15.34it/s]

MNLI entailment:  41%|████      | 554/1367 [00:36<00:51, 15.69it/s]
MNLI entailment:  41%|████      | 556/1367 [00:36<00:51, 15.75it/s]

MNLI entailment:  41%|████      | 558/1367 [00:36<00:50, 15.93it/s]
MNLI entailment:  41%|████      | 560/1367 [00:36<00:49, 16.17it/s]

MNLI entailment:  41%|████      | 562/1367 [00:36<00:49, 16.32it/s]
MNLI entailment:  41%|████▏     | 564/1367 [00:36<00:49, 16.09it/s]

MNLI entailment:  41%|████▏     | 566/1367 [00:37<00:49, 16.25it/s]
MNLI entailment:  42%|████▏     | 568/1367 [00:37<00:48, 16.32it/s]

MNLI entailment:  42%|████▏     | 570/1367 [00:37<00:49, 16.26it/s]
MNLI entailment:  42%|████▏     | 572/1367 [00:37<00:48, 16.39it/s]

MNLI entailment:  42%|████▏     | 574/1367 [00:37<00:47, 16.82it/s]
MNLI entailment:  42%|████▏     | 576/1367 [00:37<00:46, 17.16it/s]

MNLI entailment:  42%|████▏     | 578/1367 [00:37<00:46, 16.98it/s]
MNLI entailment:  42%|████▏     | 580/1367 [00:37<00:46, 17.03it/s]

MNLI entailment:  43%|████▎     | 582/1367 [00:37<00:44, 17.72it/s]
MNLI entailment:  43%|████▎     | 584/1367 [00:38<00:43, 17.85it/s]

MNLI entailment:  43%|████▎     | 586/1367 [00:38<00:44, 17.51it/s]
MNLI entailment:  43%|████▎     | 588/1367 [00:38<00:45, 16.98it/s]

MNLI entailment:  43%|████▎     | 590/1367 [00:38<00:46, 16.86it/s]
MNLI entailment:  43%|████▎     | 592/1367 [00:38<00:46, 16.78it/s]

MNLI entailment:  43%|████▎     | 594/1367 [00:38<00:46, 16.75it/s]
MNLI entailment:  44%|████▎     | 596/1367 [00:38<00:46, 16.45it/s]

MNLI entailment:  44%|████▎     | 598/1367 [00:38<00:45, 16.99it/s]
MNLI entailment:  44%|████▍     | 600/1367 [00:39<00:45, 16.87it/s]

MNLI entailment:  44%|████▍     | 602/1367 [00:39<00:45, 16.80it/s]
MNLI entailment:  44%|████▍     | 604/1367 [00:39<00:45, 16.66it/s]

MNLI entailment:  44%|████▍     | 606/1367 [00:39<00:45, 16.67it/s]
MNLI entailment:  44%|████▍     | 608/1367 [00:39<00:45, 16.78it/s]

MNLI entailment:  45%|████▍     | 610/1367 [00:39<00:45, 16.74it/s]
MNLI entailment:  45%|████▍     | 612/1367 [00:39<00:44, 17.09it/s]

MNLI entailment:  45%|████▍     | 614/1367 [00:39<00:45, 16.64it/s]
MNLI entailment:  45%|████▌     | 616/1367 [00:39<00:44, 16.72it/s]

MNLI entailment:  45%|████▌     | 618/1367 [00:40<00:43, 17.09it/s]
MNLI entailment:  45%|████▌     | 620/1367 [00:40<00:43, 17.02it/s]

MNLI entailment:  46%|████▌     | 622/1367 [00:40<00:43, 17.28it/s]
MNLI entailment:  46%|████▌     | 624/1367 [00:40<00:43, 17.14it/s]

MNLI entailment:  46%|████▌     | 626/1367 [00:40<00:43, 17.03it/s]
MNLI entailment:  46%|████▌     | 628/1367 [00:40<00:43, 16.97it/s]

MNLI entailment:  46%|████▌     | 630/1367 [00:40<00:42, 17.29it/s]
MNLI entailment:  46%|████▌     | 632/1367 [00:40<00:42, 17.10it/s]

MNLI entailment:  46%|████▋     | 634/1367 [00:41<00:42, 17.36it/s]
MNLI entailment:  47%|████▋     | 636/1367 [00:41<00:42, 17.14it/s]

MNLI entailment:  47%|████▋     | 638/1367 [00:41<00:41, 17.38it/s]
MNLI entailment:  47%|████▋     | 640/1367 [00:41<00:41, 17.61it/s]

MNLI entailment:  47%|████▋     | 642/1367 [00:41<00:40, 17.76it/s]
MNLI entailment:  47%|████▋     | 644/1367 [00:41<00:41, 17.39it/s]

MNLI entailment:  47%|████▋     | 646/1367 [00:41<00:40, 17.61it/s]
MNLI entailment:  47%|████▋     | 648/1367 [00:41<00:40, 17.80it/s]

MNLI entailment:  48%|████▊     | 650/1367 [00:41<00:39, 18.27it/s]
MNLI entailment:  48%|████▊     | 652/1367 [00:42<00:40, 17.62it/s]

MNLI entailment:  48%|████▊     | 654/1367 [00:42<00:41, 17.33it/s]
MNLI entailment:  48%|████▊     | 656/1367 [00:42<00:41, 17.13it/s]

MNLI entailment:  48%|████▊     | 658/1367 [00:42<00:40, 17.37it/s]
MNLI entailment:  48%|████▊     | 660/1367 [00:42<00:41, 17.20it/s]

MNLI entailment:  48%|████▊     | 662/1367 [00:42<00:41, 17.11it/s]
MNLI entailment:  49%|████▊     | 664/1367 [00:42<00:40, 17.39it/s]

MNLI entailment:  49%|████▊     | 666/1367 [00:42<00:40, 17.16it/s]
MNLI entailment:  49%|████▉     | 668/1367 [00:42<00:40, 17.11it/s]

MNLI entailment:  49%|████▉     | 670/1367 [00:43<00:40, 17.32it/s]
MNLI entailment:  49%|████▉     | 672/1367 [00:43<00:41, 16.85it/s]

MNLI entailment:  49%|████▉     | 674/1367 [00:43<00:41, 16.82it/s]
MNLI entailment:  49%|████▉     | 676/1367 [00:43<00:41, 16.80it/s]

MNLI entailment:  50%|████▉     | 678/1367 [00:43<00:39, 17.23it/s]
MNLI entailment:  50%|████▉     | 680/1367 [00:43<00:39, 17.42it/s]

MNLI entailment:  50%|████▉     | 682/1367 [00:43<00:40, 16.96it/s]
MNLI entailment:  50%|█████     | 684/1367 [00:43<00:39, 17.21it/s]

MNLI entailment:  50%|█████     | 686/1367 [00:44<00:38, 17.85it/s]
MNLI entailment:  50%|█████     | 688/1367 [00:44<00:38, 17.49it/s]

MNLI entailment:  50%|█████     | 690/1367 [00:44<00:39, 17.32it/s]
MNLI entailment:  51%|█████     | 692/1367 [00:44<00:39, 17.12it/s]

MNLI entailment:  51%|█████     | 694/1367 [00:44<00:38, 17.40it/s]
MNLI entailment:  51%|█████     | 696/1367 [00:44<00:38, 17.64it/s]

MNLI entailment:  51%|█████     | 698/1367 [00:44<00:38, 17.43it/s]
MNLI entailment:  51%|█████     | 700/1367 [00:44<00:38, 17.27it/s]

MNLI entailment:  51%|█████▏    | 702/1367 [00:44<00:39, 16.87it/s]
MNLI entailment:  51%|█████▏    | 704/1367 [00:45<00:39, 16.85it/s]

MNLI entailment:  52%|█████▏    | 706/1367 [00:45<00:39, 16.85it/s]
MNLI entailment:  52%|█████▏    | 708/1367 [00:45<00:39, 16.84it/s]

MNLI entailment:  52%|█████▏    | 710/1367 [00:45<00:39, 16.83it/s]
MNLI entailment:  52%|█████▏    | 712/1367 [00:45<00:38, 16.81it/s]

MNLI entailment:  52%|█████▏    | 714/1367 [00:45<00:38, 17.18it/s]
MNLI entailment:  52%|█████▏    | 716/1367 [00:45<00:37, 17.45it/s]

MNLI entailment:  53%|█████▎    | 718/1367 [00:45<00:37, 17.51it/s]
MNLI entailment:  53%|█████▎    | 720/1367 [00:46<00:37, 17.28it/s]

MNLI entailment:  53%|█████▎    | 722/1367 [00:46<00:37, 17.11it/s]
MNLI entailment:  53%|█████▎    | 724/1367 [00:46<00:37, 16.97it/s]

MNLI entailment:  53%|█████▎    | 726/1367 [00:46<00:37, 17.02it/s]
MNLI entailment:  53%|█████▎    | 728/1367 [00:46<00:37, 16.94it/s]

MNLI entailment:  53%|█████▎    | 730/1367 [00:46<00:36, 17.25it/s]
MNLI entailment:  54%|█████▎    | 732/1367 [00:46<00:37, 17.12it/s]

MNLI entailment:  54%|█████▎    | 734/1367 [00:46<00:37, 17.05it/s]
MNLI entailment:  54%|█████▍    | 736/1367 [00:46<00:38, 16.41it/s]

MNLI entailment:  54%|█████▍    | 738/1367 [00:47<00:37, 16.57it/s]
MNLI entailment:  54%|█████▍    | 740/1367 [00:47<00:37, 16.65it/s]

MNLI entailment:  54%|█████▍    | 742/1367 [00:47<00:36, 17.09it/s]
MNLI entailment:  54%|█████▍    | 744/1367 [00:47<00:36, 16.91it/s]

MNLI entailment:  55%|█████▍    | 746/1367 [00:47<00:36, 16.79it/s]
MNLI entailment:  55%|█████▍    | 748/1367 [00:47<00:36, 16.77it/s]

MNLI entailment:  55%|█████▍    | 750/1367 [00:47<00:36, 17.06it/s]
MNLI entailment:  55%|█████▌    | 752/1367 [00:47<00:36, 17.02it/s]

MNLI entailment:  55%|█████▌    | 754/1367 [00:48<00:36, 16.93it/s]
MNLI entailment:  55%|█████▌    | 756/1367 [00:48<00:36, 16.65it/s]

MNLI entailment:  55%|█████▌    | 758/1367 [00:48<00:36, 16.69it/s]
MNLI entailment:  56%|█████▌    | 760/1367 [00:48<00:36, 16.66it/s]

MNLI entailment:  56%|█████▌    | 762/1367 [00:48<00:36, 16.68it/s]
MNLI entailment:  56%|█████▌    | 764/1367 [00:48<00:36, 16.74it/s]

MNLI entailment:  56%|█████▌    | 766/1367 [00:48<00:35, 17.10it/s]
MNLI entailment:  56%|█████▌    | 768/1367 [00:48<00:35, 17.07it/s]

MNLI entailment:  56%|█████▋    | 770/1367 [00:48<00:34, 17.32it/s]
MNLI entailment:  56%|█████▋    | 772/1367 [00:49<00:34, 17.16it/s]

MNLI entailment:  57%|█████▋    | 774/1367 [00:49<00:34, 16.99it/s]
MNLI entailment:  57%|█████▋    | 776/1367 [00:49<00:35, 16.85it/s]

MNLI entailment:  57%|█████▋    | 778/1367 [00:49<00:34, 17.19it/s]
MNLI entailment:  57%|█████▋    | 780/1367 [00:49<00:34, 16.82it/s]

MNLI entailment:  57%|█████▋    | 782/1367 [00:49<00:34, 17.16it/s]
MNLI entailment:  57%|█████▋    | 784/1367 [00:49<00:33, 17.38it/s]

MNLI entailment:  57%|█████▋    | 786/1367 [00:49<00:33, 17.17it/s]
MNLI entailment:  58%|█████▊    | 788/1367 [00:50<00:33, 17.44it/s]

MNLI entailment:  58%|█████▊    | 790/1367 [00:50<00:33, 17.12it/s]
MNLI entailment:  58%|█████▊    | 792/1367 [00:50<00:33, 17.00it/s]

MNLI entailment:  58%|█████▊    | 794/1367 [00:50<00:33, 17.28it/s]
MNLI entailment:  58%|█████▊    | 796/1367 [00:50<00:33, 17.14it/s]

MNLI entailment:  58%|█████▊    | 798/1367 [00:50<00:32, 17.32it/s]
MNLI entailment:  59%|█████▊    | 801/1367 [00:50<00:28, 19.68it/s]

MNLI entailment:  59%|█████▊    | 803/1367 [00:50<00:30, 18.21it/s]
MNLI entailment:  59%|█████▉    | 805/1367 [00:50<00:31, 17.77it/s]

MNLI entailment:  59%|█████▉    | 807/1367 [00:51<00:32, 17.46it/s]
MNLI entailment:  59%|█████▉    | 809/1367 [00:51<00:32, 16.98it/s]

MNLI entailment:  59%|█████▉    | 811/1367 [00:51<00:32, 16.91it/s]
MNLI entailment:  59%|█████▉    | 813/1367 [00:51<00:33, 16.66it/s]

MNLI entailment:  60%|█████▉    | 815/1367 [00:51<00:33, 16.55it/s]
MNLI entailment:  60%|█████▉    | 817/1367 [00:51<00:33, 16.42it/s]

MNLI entailment:  60%|█████▉    | 819/1367 [00:51<00:33, 16.32it/s]
MNLI entailment:  60%|██████    | 821/1367 [00:51<00:33, 16.51it/s]

MNLI entailment:  60%|██████    | 823/1367 [00:52<00:32, 16.62it/s]
MNLI entailment:  60%|██████    | 825/1367 [00:52<00:32, 16.71it/s]

MNLI entailment:  60%|██████    | 827/1367 [00:52<00:32, 16.52it/s]
MNLI entailment:  61%|██████    | 829/1367 [00:52<00:32, 16.63it/s]

MNLI entailment:  61%|██████    | 831/1367 [00:52<00:31, 17.04it/s]
MNLI entailment:  61%|██████    | 833/1367 [00:52<00:31, 17.01it/s]

MNLI entailment:  61%|██████    | 835/1367 [00:52<00:32, 16.36it/s]
MNLI entailment:  61%|██████    | 837/1367 [00:52<00:31, 16.57it/s]

MNLI entailment:  61%|██████▏   | 839/1367 [00:53<00:31, 16.70it/s]
MNLI entailment:  62%|██████▏   | 841/1367 [00:53<00:30, 17.16it/s]

MNLI entailment:  62%|██████▏   | 843/1367 [00:53<00:31, 16.87it/s]
MNLI entailment:  62%|██████▏   | 845/1367 [00:53<00:31, 16.83it/s]

MNLI entailment:  62%|██████▏   | 847/1367 [00:53<00:30, 17.24it/s]
MNLI entailment:  62%|██████▏   | 849/1367 [00:53<00:30, 16.88it/s]

MNLI entailment:  62%|██████▏   | 851/1367 [00:53<00:30, 16.93it/s]
MNLI entailment:  62%|██████▏   | 853/1367 [00:53<00:30, 16.93it/s]

MNLI entailment:  63%|██████▎   | 855/1367 [00:53<00:30, 16.95it/s]
MNLI entailment:  63%|██████▎   | 857/1367 [00:54<00:30, 16.67it/s]

MNLI entailment:  63%|██████▎   | 859/1367 [00:54<00:30, 16.74it/s]
MNLI entailment:  63%|██████▎   | 861/1367 [00:54<00:29, 17.17it/s]

MNLI entailment:  63%|██████▎   | 863/1367 [00:54<00:29, 17.13it/s]
MNLI entailment:  63%|██████▎   | 865/1367 [00:54<00:29, 17.07it/s]

MNLI entailment:  63%|██████▎   | 867/1367 [00:54<00:30, 16.44it/s]
MNLI entailment:  64%|██████▎   | 869/1367 [00:54<00:30, 16.58it/s]

MNLI entailment:  64%|██████▎   | 871/1367 [00:54<00:29, 16.64it/s]
MNLI entailment:  64%|██████▍   | 873/1367 [00:55<00:28, 17.16it/s]

MNLI entailment:  64%|██████▍   | 875/1367 [00:55<00:28, 17.06it/s]
MNLI entailment:  64%|██████▍   | 877/1367 [00:55<00:28, 17.03it/s]

MNLI entailment:  64%|██████▍   | 879/1367 [00:55<00:28, 17.37it/s]
MNLI entailment:  64%|██████▍   | 881/1367 [00:55<00:27, 17.53it/s]

MNLI entailment:  65%|██████▍   | 883/1367 [00:55<00:27, 17.36it/s]
MNLI entailment:  65%|██████▍   | 885/1367 [00:55<00:28, 17.21it/s]

MNLI entailment:  65%|██████▍   | 887/1367 [00:55<00:28, 16.85it/s]
MNLI entailment:  65%|██████▌   | 889/1367 [00:55<00:28, 16.95it/s]

MNLI entailment:  65%|██████▌   | 891/1367 [00:56<00:28, 16.94it/s]
MNLI entailment:  65%|██████▌   | 893/1367 [00:56<00:27, 16.98it/s]

MNLI entailment:  65%|██████▌   | 895/1367 [00:56<00:27, 16.97it/s]
MNLI entailment:  66%|██████▌   | 897/1367 [00:56<00:27, 17.34it/s]

MNLI entailment:  66%|██████▌   | 899/1367 [00:56<00:27, 17.31it/s]
MNLI entailment:  66%|██████▌   | 901/1367 [00:56<00:27, 17.21it/s]

MNLI entailment:  66%|██████▌   | 903/1367 [00:56<00:26, 17.52it/s]
MNLI entailment:  66%|██████▌   | 905/1367 [00:56<00:26, 17.32it/s]

MNLI entailment:  66%|██████▋   | 907/1367 [00:57<00:26, 17.24it/s]
MNLI entailment:  66%|██████▋   | 909/1367 [00:57<00:26, 17.55it/s]

MNLI entailment:  67%|██████▋   | 911/1367 [00:57<00:26, 17.36it/s]
MNLI entailment:  67%|██████▋   | 913/1367 [00:57<00:25, 17.63it/s]

MNLI entailment:  67%|██████▋   | 915/1367 [00:57<00:25, 17.43it/s]
MNLI entailment:  67%|██████▋   | 917/1367 [00:57<00:25, 17.67it/s]

MNLI entailment:  67%|██████▋   | 919/1367 [00:57<00:25, 17.89it/s]
MNLI entailment:  67%|██████▋   | 921/1367 [00:57<00:25, 17.60it/s]

MNLI entailment:  68%|██████▊   | 923/1367 [00:57<00:25, 17.15it/s]
MNLI entailment:  68%|██████▊   | 925/1367 [00:58<00:25, 17.07it/s]

MNLI entailment:  68%|██████▊   | 927/1367 [00:58<00:25, 17.04it/s]
MNLI entailment:  68%|██████▊   | 929/1367 [00:58<00:25, 17.00it/s]

MNLI entailment:  68%|██████▊   | 932/1367 [00:58<00:21, 19.96it/s]
MNLI entailment:  68%|██████▊   | 935/1367 [00:58<00:23, 18.26it/s]

MNLI entailment:  69%|██████▊   | 937/1367 [00:58<00:24, 17.89it/s]
MNLI entailment:  69%|██████▊   | 939/1367 [00:58<00:24, 17.41it/s]

MNLI entailment:  69%|██████▉   | 941/1367 [00:58<00:24, 17.18it/s]
MNLI entailment:  69%|██████▉   | 943/1367 [00:59<00:24, 17.38it/s]

MNLI entailment:  69%|██████▉   | 945/1367 [00:59<00:24, 17.25it/s]
MNLI entailment:  69%|██████▉   | 947/1367 [00:59<00:24, 16.82it/s]

MNLI entailment:  69%|██████▉   | 949/1367 [00:59<00:24, 16.79it/s]
MNLI entailment:  70%|██████▉   | 951/1367 [00:59<00:24, 16.77it/s]

MNLI entailment:  70%|██████▉   | 953/1367 [00:59<00:24, 17.18it/s]
MNLI entailment:  70%|██████▉   | 955/1367 [00:59<00:23, 17.51it/s]

MNLI entailment:  70%|███████   | 957/1367 [00:59<00:23, 17.67it/s]
MNLI entailment:  70%|███████   | 959/1367 [00:59<00:22, 17.77it/s]

MNLI entailment:  70%|███████   | 961/1367 [01:00<00:23, 17.16it/s]
MNLI entailment:  70%|███████   | 963/1367 [01:00<00:22, 17.81it/s]

MNLI entailment:  71%|███████   | 965/1367 [01:00<00:22, 17.52it/s]
MNLI entailment:  71%|███████   | 967/1367 [01:00<00:23, 17.35it/s]

MNLI entailment:  71%|███████   | 969/1367 [01:00<00:24, 16.53it/s]
MNLI entailment:  71%|███████   | 971/1367 [01:00<00:23, 16.69it/s]

MNLI entailment:  71%|███████   | 973/1367 [01:00<00:23, 16.51it/s]
MNLI entailment:  71%|███████▏  | 975/1367 [01:00<00:23, 17.01it/s]

MNLI entailment:  71%|███████▏  | 977/1367 [01:01<00:22, 16.98it/s]
MNLI entailment:  72%|███████▏  | 979/1367 [01:01<00:22, 17.22it/s]

MNLI entailment:  72%|███████▏  | 981/1367 [01:01<00:22, 17.45it/s]
MNLI entailment:  72%|███████▏  | 983/1367 [01:01<00:21, 18.11it/s]

MNLI entailment:  72%|███████▏  | 985/1367 [01:01<00:21, 18.17it/s]
MNLI entailment:  72%|███████▏  | 987/1367 [01:01<00:21, 17.88it/s]

MNLI entailment:  72%|███████▏  | 989/1367 [01:01<00:21, 17.60it/s]
MNLI entailment:  72%|███████▏  | 991/1367 [01:01<00:21, 17.34it/s]

MNLI entailment:  73%|███████▎  | 993/1367 [01:01<00:21, 17.59it/s]
MNLI entailment:  73%|███████▎  | 995/1367 [01:02<00:20, 17.78it/s]

MNLI entailment:  73%|███████▎  | 997/1367 [01:02<00:20, 17.87it/s]
MNLI entailment:  73%|███████▎  | 999/1367 [01:02<00:20, 17.91it/s]

MNLI entailment:  73%|███████▎  | 1001/1367 [01:02<00:20, 17.61it/s]
MNLI entailment:  73%|███████▎  | 1003/1367 [01:02<00:19, 18.25it/s]

MNLI entailment:  74%|███████▎  | 1005/1367 [01:02<00:20, 17.48it/s]
MNLI entailment:  74%|███████▎  | 1007/1367 [01:02<00:20, 17.63it/s]

MNLI entailment:  74%|███████▍  | 1009/1367 [01:02<00:20, 17.38it/s]
MNLI entailment:  74%|███████▍  | 1011/1367 [01:02<00:20, 17.19it/s]

MNLI entailment:  74%|███████▍  | 1013/1367 [01:03<00:20, 17.12it/s]
MNLI entailment:  74%|███████▍  | 1015/1367 [01:03<00:20, 17.40it/s]

MNLI entailment:  74%|███████▍  | 1017/1367 [01:03<00:19, 18.08it/s]
MNLI entailment:  75%|███████▍  | 1019/1367 [01:03<00:19, 17.67it/s]

MNLI entailment:  75%|███████▍  | 1021/1367 [01:03<00:19, 17.39it/s]
MNLI entailment:  75%|███████▍  | 1023/1367 [01:03<00:20, 17.15it/s]

MNLI entailment:  75%|███████▍  | 1025/1367 [01:03<00:19, 17.10it/s]
MNLI entailment:  75%|███████▌  | 1027/1367 [01:03<00:19, 17.08it/s]

MNLI entailment:  75%|███████▌  | 1029/1367 [01:04<00:19, 17.38it/s]
MNLI entailment:  75%|███████▌  | 1031/1367 [01:04<00:19, 16.94it/s]

MNLI entailment:  76%|███████▌  | 1033/1367 [01:04<00:19, 16.78it/s]
MNLI entailment:  76%|███████▌  | 1035/1367 [01:04<00:19, 17.21it/s]

MNLI entailment:  76%|███████▌  | 1037/1367 [01:04<00:19, 17.12it/s]
MNLI entailment:  76%|███████▌  | 1039/1367 [01:04<00:18, 17.42it/s]

MNLI entailment:  76%|███████▌  | 1041/1367 [01:04<00:18, 17.29it/s]
MNLI entailment:  76%|███████▋  | 1043/1367 [01:04<00:18, 17.16it/s]

MNLI entailment:  76%|███████▋  | 1045/1367 [01:04<00:18, 17.08it/s]
MNLI entailment:  77%|███████▋  | 1047/1367 [01:05<00:18, 16.97it/s]

MNLI entailment:  77%|███████▋  | 1049/1367 [01:05<00:18, 16.98it/s]
MNLI entailment:  77%|███████▋  | 1051/1367 [01:05<00:18, 17.01it/s]

MNLI entailment:  77%|███████▋  | 1053/1367 [01:05<00:18, 17.01it/s]
MNLI entailment:  77%|███████▋  | 1055/1367 [01:05<00:18, 17.03it/s]

MNLI entailment:  77%|███████▋  | 1057/1367 [01:05<00:17, 17.24it/s]
MNLI entailment:  77%|███████▋  | 1059/1367 [01:05<00:17, 17.19it/s]

MNLI entailment:  78%|███████▊  | 1061/1367 [01:05<00:17, 17.13it/s]
MNLI entailment:  78%|███████▊  | 1063/1367 [01:06<00:18, 16.87it/s]

MNLI entailment:  78%|███████▊  | 1065/1367 [01:06<00:17, 16.93it/s]
MNLI entailment:  78%|███████▊  | 1067/1367 [01:06<00:17, 16.93it/s]

MNLI entailment:  78%|███████▊  | 1069/1367 [01:06<00:17, 16.92it/s]
MNLI entailment:  78%|███████▊  | 1071/1367 [01:06<00:17, 17.36it/s]

MNLI entailment:  78%|███████▊  | 1073/1367 [01:06<00:17, 17.28it/s]
MNLI entailment:  79%|███████▊  | 1075/1367 [01:06<00:16, 17.22it/s]

MNLI entailment:  79%|███████▉  | 1077/1367 [01:06<00:17, 16.89it/s]
MNLI entailment:  79%|███████▉  | 1079/1367 [01:06<00:16, 17.24it/s]

MNLI entailment:  79%|███████▉  | 1081/1367 [01:07<00:16, 17.63it/s]
MNLI entailment:  79%|███████▉  | 1083/1367 [01:07<00:15, 18.28it/s]

MNLI entailment:  79%|███████▉  | 1085/1367 [01:07<00:15, 18.28it/s]
MNLI entailment:  80%|███████▉  | 1087/1367 [01:07<00:15, 17.89it/s]

MNLI entailment:  80%|███████▉  | 1089/1367 [01:07<00:15, 17.65it/s]
MNLI entailment:  80%|███████▉  | 1091/1367 [01:07<00:15, 17.48it/s]

MNLI entailment:  80%|███████▉  | 1093/1367 [01:07<00:15, 17.70it/s]
MNLI entailment:  80%|████████  | 1095/1367 [01:07<00:15, 17.98it/s]

MNLI entailment:  80%|████████  | 1097/1367 [01:07<00:15, 17.63it/s]
MNLI entailment:  80%|████████  | 1099/1367 [01:08<00:15, 17.83it/s]

MNLI entailment:  81%|████████  | 1101/1367 [01:08<00:15, 17.55it/s]
MNLI entailment:  81%|████████  | 1103/1367 [01:08<00:15, 17.38it/s]

MNLI entailment:  81%|████████  | 1105/1367 [01:08<00:15, 17.02it/s]
MNLI entailment:  81%|████████  | 1107/1367 [01:08<00:15, 16.73it/s]

MNLI entailment:  81%|████████  | 1109/1367 [01:08<00:14, 17.24it/s]
MNLI entailment:  81%|████████▏ | 1111/1367 [01:08<00:15, 16.97it/s]

MNLI entailment:  81%|████████▏ | 1113/1367 [01:08<00:14, 17.35it/s]
MNLI entailment:  82%|████████▏ | 1115/1367 [01:08<00:14, 17.21it/s]

MNLI entailment:  82%|████████▏ | 1117/1367 [01:09<00:14, 17.08it/s]
MNLI entailment:  82%|████████▏ | 1119/1367 [01:09<00:14, 17.00it/s]

MNLI entailment:  82%|████████▏ | 1121/1367 [01:09<00:14, 17.35it/s]
MNLI entailment:  82%|████████▏ | 1123/1367 [01:09<00:13, 17.62it/s]

MNLI entailment:  82%|████████▏ | 1125/1367 [01:09<00:13, 17.42it/s]
MNLI entailment:  82%|████████▏ | 1127/1367 [01:09<00:14, 17.03it/s]

MNLI entailment:  83%|████████▎ | 1129/1367 [01:09<00:14, 16.75it/s]
MNLI entailment:  83%|████████▎ | 1131/1367 [01:09<00:14, 16.85it/s]

MNLI entailment:  83%|████████▎ | 1133/1367 [01:10<00:13, 17.19it/s]
MNLI entailment:  83%|████████▎ | 1135/1367 [01:10<00:13, 17.46it/s]

MNLI entailment:  83%|████████▎ | 1137/1367 [01:10<00:13, 17.07it/s]
MNLI entailment:  83%|████████▎ | 1139/1367 [01:10<00:13, 17.06it/s]

MNLI entailment:  83%|████████▎ | 1141/1367 [01:10<00:13, 17.06it/s]
MNLI entailment:  84%|████████▎ | 1143/1367 [01:10<00:13, 16.84it/s]

MNLI entailment:  84%|████████▍ | 1145/1367 [01:10<00:12, 17.64it/s]
MNLI entailment:  84%|████████▍ | 1147/1367 [01:10<00:12, 17.12it/s]

MNLI entailment:  84%|████████▍ | 1149/1367 [01:10<00:12, 17.05it/s]
MNLI entailment:  84%|████████▍ | 1151/1367 [01:11<00:12, 17.83it/s]

MNLI entailment:  84%|████████▍ | 1153/1367 [01:11<00:11, 17.97it/s]
MNLI entailment:  84%|████████▍ | 1155/1367 [01:11<00:12, 17.40it/s]

MNLI entailment:  85%|████████▍ | 1157/1367 [01:11<00:12, 17.10it/s]
MNLI entailment:  85%|████████▍ | 1159/1367 [01:11<00:11, 17.49it/s]

MNLI entailment:  85%|████████▍ | 1161/1367 [01:11<00:11, 17.36it/s]
MNLI entailment:  85%|████████▌ | 1163/1367 [01:11<00:11, 17.33it/s]

MNLI entailment:  85%|████████▌ | 1165/1367 [01:11<00:11, 17.61it/s]
MNLI entailment:  85%|████████▌ | 1167/1367 [01:11<00:11, 17.45it/s]

MNLI entailment:  86%|████████▌ | 1169/1367 [01:12<00:11, 17.33it/s]
MNLI entailment:  86%|████████▌ | 1171/1367 [01:12<00:11, 17.63it/s]

MNLI entailment:  86%|████████▌ | 1173/1367 [01:12<00:11, 17.47it/s]
MNLI entailment:  86%|████████▌ | 1175/1367 [01:12<00:11, 17.32it/s]

MNLI entailment:  86%|████████▌ | 1177/1367 [01:12<00:10, 17.62it/s]
MNLI entailment:  86%|████████▌ | 1179/1367 [01:12<00:10, 17.20it/s]

MNLI entailment:  86%|████████▋ | 1181/1367 [01:12<00:11, 16.83it/s]
MNLI entailment:  87%|████████▋ | 1183/1367 [01:12<00:10, 16.83it/s]

MNLI entailment:  87%|████████▋ | 1185/1367 [01:13<00:10, 16.88it/s]
MNLI entailment:  87%|████████▋ | 1187/1367 [01:13<00:10, 16.89it/s]

MNLI entailment:  87%|████████▋ | 1189/1367 [01:13<00:10, 17.71it/s]
MNLI entailment:  87%|████████▋ | 1191/1367 [01:13<00:10, 17.50it/s]

MNLI entailment:  87%|████████▋ | 1193/1367 [01:13<00:10, 17.37it/s]
MNLI entailment:  87%|████████▋ | 1195/1367 [01:13<00:10, 16.99it/s]

MNLI entailment:  88%|████████▊ | 1197/1367 [01:13<00:10, 16.96it/s]
MNLI entailment:  88%|████████▊ | 1199/1367 [01:13<00:09, 16.98it/s]

MNLI entailment:  88%|████████▊ | 1201/1367 [01:13<00:09, 16.87it/s]
MNLI entailment:  88%|████████▊ | 1203/1367 [01:14<00:09, 16.41it/s]

MNLI entailment:  88%|████████▊ | 1205/1367 [01:14<00:09, 16.50it/s]
MNLI entailment:  88%|████████▊ | 1207/1367 [01:14<00:09, 16.31it/s]

MNLI entailment:  88%|████████▊ | 1209/1367 [01:14<00:09, 16.18it/s]
MNLI entailment:  89%|████████▊ | 1211/1367 [01:14<00:09, 16.22it/s]

MNLI entailment:  89%|████████▊ | 1213/1367 [01:14<00:09, 15.92it/s]
MNLI entailment:  89%|████████▉ | 1215/1367 [01:14<00:09, 15.79it/s]

MNLI entailment:  89%|████████▉ | 1217/1367 [01:14<00:09, 16.07it/s]
MNLI entailment:  89%|████████▉ | 1219/1367 [01:15<00:08, 16.72it/s]

MNLI entailment:  89%|████████▉ | 1221/1367 [01:15<00:09, 15.85it/s]
MNLI entailment:  89%|████████▉ | 1223/1367 [01:15<00:09, 15.95it/s]

MNLI entailment:  90%|████████▉ | 1225/1367 [01:15<00:08, 15.99it/s]
MNLI entailment:  90%|████████▉ | 1228/1367 [01:15<00:07, 18.50it/s]

MNLI entailment:  90%|████████▉ | 1230/1367 [01:15<00:07, 17.74it/s]
MNLI entailment:  90%|█████████ | 1232/1367 [01:15<00:07, 17.71it/s]

MNLI entailment:  90%|█████████ | 1234/1367 [01:15<00:07, 17.87it/s]
MNLI entailment:  90%|█████████ | 1236/1367 [01:16<00:07, 18.19it/s]

MNLI entailment:  91%|█████████ | 1239/1367 [01:16<00:06, 19.94it/s]
MNLI entailment:  91%|█████████ | 1241/1367 [01:16<00:06, 18.65it/s]

MNLI entailment:  91%|█████████ | 1243/1367 [01:16<00:06, 18.27it/s]
MNLI entailment:  91%|█████████ | 1245/1367 [01:16<00:06, 17.59it/s]

MNLI entailment:  91%|█████████ | 1247/1367 [01:16<00:07, 16.86it/s]
MNLI entailment:  91%|█████████▏| 1249/1367 [01:16<00:06, 17.21it/s]

MNLI entailment:  92%|█████████▏| 1251/1367 [01:16<00:07, 16.55it/s]
MNLI entailment:  92%|█████████▏| 1253/1367 [01:17<00:06, 16.50it/s]

MNLI entailment:  92%|█████████▏| 1255/1367 [01:17<00:06, 16.81it/s]
MNLI entailment:  92%|█████████▏| 1257/1367 [01:17<00:06, 16.68it/s]

MNLI entailment:  92%|█████████▏| 1259/1367 [01:17<00:06, 16.99it/s]
MNLI entailment:  92%|█████████▏| 1261/1367 [01:17<00:06, 16.86it/s]

MNLI entailment:  92%|█████████▏| 1263/1367 [01:17<00:06, 16.50it/s]
MNLI entailment:  93%|█████████▎| 1265/1367 [01:17<00:06, 16.45it/s]

MNLI entailment:  93%|█████████▎| 1267/1367 [01:17<00:06, 16.41it/s]
MNLI entailment:  93%|█████████▎| 1269/1367 [01:18<00:05, 16.42it/s]

MNLI entailment:  93%|█████████▎| 1271/1367 [01:18<00:05, 16.40it/s]
MNLI entailment:  93%|█████████▎| 1273/1367 [01:18<00:05, 16.20it/s]

MNLI entailment:  93%|█████████▎| 1275/1367 [01:18<00:05, 16.04it/s]
MNLI entailment:  93%|█████████▎| 1277/1367 [01:18<00:05, 15.90it/s]

MNLI entailment:  94%|█████████▎| 1279/1367 [01:18<00:05, 16.35it/s]
MNLI entailment:  94%|█████████▎| 1281/1367 [01:18<00:05, 15.78it/s]

MNLI entailment:  94%|█████████▍| 1283/1367 [01:18<00:05, 16.27it/s]
MNLI entailment:  94%|█████████▍| 1285/1367 [01:19<00:05, 16.16it/s]

MNLI entailment:  94%|█████████▍| 1287/1367 [01:19<00:05, 15.93it/s]
MNLI entailment:  94%|█████████▍| 1289/1367 [01:19<00:05, 15.49it/s]

MNLI entailment:  94%|█████████▍| 1291/1367 [01:19<00:04, 16.09it/s]
MNLI entailment:  95%|█████████▍| 1293/1367 [01:19<00:04, 16.20it/s]

MNLI entailment:  95%|█████████▍| 1295/1367 [01:19<00:04, 15.98it/s]
MNLI entailment:  95%|█████████▍| 1297/1367 [01:19<00:04, 16.45it/s]

MNLI entailment:  95%|█████████▌| 1299/1367 [01:19<00:04, 16.29it/s]
MNLI entailment:  95%|█████████▌| 1301/1367 [01:19<00:03, 16.51it/s]

MNLI entailment:  95%|█████████▌| 1303/1367 [01:20<00:03, 16.36it/s]
MNLI entailment:  95%|█████████▌| 1305/1367 [01:20<00:03, 16.13it/s]

MNLI entailment:  96%|█████████▌| 1307/1367 [01:20<00:03, 15.92it/s]
MNLI entailment:  96%|█████████▌| 1309/1367 [01:20<00:03, 15.66it/s]

MNLI entailment:  96%|█████████▌| 1312/1367 [01:20<00:03, 17.90it/s]
MNLI entailment:  96%|█████████▌| 1314/1367 [01:20<00:03, 17.09it/s]

MNLI entailment:  96%|█████████▋| 1316/1367 [01:20<00:03, 16.90it/s]
MNLI entailment:  96%|█████████▋| 1318/1367 [01:21<00:02, 17.10it/s]

MNLI entailment:  97%|█████████▋| 1320/1367 [01:21<00:02, 16.60it/s]
MNLI entailment:  97%|█████████▋| 1322/1367 [01:21<00:02, 17.34it/s]

MNLI entailment:  97%|█████████▋| 1324/1367 [01:21<00:02, 17.48it/s]
MNLI entailment:  97%|█████████▋| 1326/1367 [01:21<00:02, 17.52it/s]

MNLI entailment:  97%|█████████▋| 1328/1367 [01:21<00:02, 16.83it/s]
MNLI entailment:  97%|█████████▋| 1330/1367 [01:21<00:02, 16.73it/s]

MNLI entailment:  97%|█████████▋| 1332/1367 [01:21<00:02, 17.15it/s]
MNLI entailment:  98%|█████████▊| 1334/1367 [01:21<00:02, 16.28it/s]

MNLI entailment:  98%|█████████▊| 1336/1367 [01:22<00:01, 16.04it/s]
MNLI entailment:  98%|█████████▊| 1338/1367 [01:22<00:01, 16.00it/s]

MNLI entailment:  98%|█████████▊| 1340/1367 [01:22<00:01, 16.10it/s]
MNLI entailment:  98%|█████████▊| 1342/1367 [01:22<00:01, 16.56it/s]

MNLI entailment:  98%|█████████▊| 1344/1367 [01:22<00:01, 15.88it/s]
MNLI entailment:  98%|█████████▊| 1346/1367 [01:22<00:01, 16.07it/s]

MNLI entailment:  99%|█████████▊| 1348/1367 [01:22<00:01, 16.53it/s]
MNLI entailment:  99%|█████████▉| 1350/1367 [01:22<00:01, 16.82it/s]

MNLI entailment:  99%|█████████▉| 1352/1367 [01:23<00:00, 16.72it/s]
MNLI entailment:  99%|█████████▉| 1354/1367 [01:23<00:00, 17.03it/s]

MNLI entailment:  99%|█████████▉| 1356/1367 [01:23<00:00, 16.17it/s]
MNLI entailment:  99%|█████████▉| 1358/1367 [01:23<00:00, 16.06it/s]

MNLI entailment:  99%|█████████▉| 1360/1367 [01:23<00:00, 15.90it/s]
MNLI entailment: 100%|█████████▉| 1362/1367 [01:23<00:00, 16.11it/s]

MNLI entailment: 100%|█████████▉| 1364/1367 [01:23<00:00, 15.99it/s]
MNLI entailment: 100%|█████████▉| 1366/1367 [01:23<00:00, 16.09it/s]
MNLI entailment: 100%|██████████| 1367/1367 [01:23<00:00, 16.28it/s]

Entailment threshold 0.4: pass 919/1367 rows with non-empty claims
Wrote /Users/momoba/Desktop/Advanced ML Project /Part3_Output/tabi_outputs_validated.csv

## 6b. View TABI outputs here (no API)

Loads **`Part3_Output/tabi_outputs.csv`** and, if present, **`tabi_outputs_validated.csv`**. Run Section 5 (TABI) and Section 6 (`tabi-validate`) first, or open the CSVs in Cursor/Excel.

In [13]:
import pandas as pd
from IPython.display import display

TAB = PROJECT_ROOT / "Part3_Output" / "tabi_outputs.csv"
VAL = PROJECT_ROOT / "Part3_Output" / "tabi_outputs_validated.csv"

if TAB.exists():
    d = pd.read_csv(TAB)
    c = d["claim"].fillna("").astype(str).str.strip()
    print("===", TAB.name, "===")
    print("rows:", len(d))
    print("non-NONE claims:", int(((c != "") & (c.str.upper() != "NONE")).sum()))
    if "parse_error" in d.columns:
        print("rows with parse_error:", int(d["parse_error"].fillna("").astype(str).str.len().gt(0).sum()))
    display(d[["chunk_id", "article_filename", "bucket", "claim", "grounds"]].head(8))
else:
    print("Missing", TAB)

if VAL.exists():
    v = pd.read_csv(VAL)
    print("\n===", VAL.name, "===")
    if "mnli_entailment_pass" in v.columns:
        passed = int(v["mnli_entailment_pass"].fillna(False).astype(bool).sum())
        print("entailment_pass=True rows:", passed, "/", len(v))
    show = v[v["mnli_entailment_pass"] == True] if "mnli_entailment_pass" in v.columns else v
    cols = [c for c in ["chunk_id", "bucket", "claim", "grounds", "mnli_entailment_prob", "mnli_entailment_pass"] if c in show.columns]
    display(show[cols].head(10))
else:
    print("\n(No validated file yet — run Section 6 `tabi-validate`.)")

=== tabi_outputs.csv ===
rows: 1367
non-NONE claims: 1361
rows with parse_error: 0

,chunk_id,article_filename,bucket,claim,grounds
0,0,Does-college-education-make-women-less-likely-...,more_probable,The impact of educational assortative mating o...,the strong negative relationship observed betw...
1,1,Does-college-education-make-women-less-likely-...,more_probable,The impact of higher education expansion on ma...,this finding might not generalise to rural ori...
2,2,Does-college-education-make-women-less-likely-...,more_probable,The impact of the hukou system on educational ...,The hukou (household registration) system...is...
3,3,Does-college-education-make-women-less-likely-...,more_probable,The causal mechanisms linking higher education...,we provide direct causal evidence of the effec...
4,4,Does-college-education-make-women-less-likely-...,more_probable,The long-term effects of the HE expansion on e...,the massive HE expansion started in 1999...the...
5,5,Does-college-education-make-women-less-likely-...,more_probable,The long-term effects of the 1999 HE expansion...,The HE expansion came as a totally unanticipat...
6,6,Does-college-education-make-women-less-likely-...,more_probable,The differential impact of HE expansion on rur...,there is only a visible jump for urban student...
7,7,Does-college-education-make-women-less-likely-...,more_probable,The specific mechanisms by which education aff...,The LPM marginal effects of women ’ s educatio...

=== tabi_outputs_validated.csv ===
entailment_pass=True rows: 919 / 1367

,chunk_id,bucket,claim,grounds,mnli_entailment_prob,mnli_entailment_pass
1,1,more_probable,The impact of higher education expansion on ma...,this finding might not generalise to rural ori...,0.864524,True
2,2,more_probable,The impact of the hukou system on educational ...,The hukou (household registration) system...is...,0.678260,True
4,4,more_probable,The long-term effects of the HE expansion on e...,the massive HE expansion started in 1999...the...,0.903421,True
6,6,more_probable,The differential impact of HE expansion on rur...,there is only a visible jump for urban student...,0.939888,True
7,7,more_probable,The specific mechanisms by which education aff...,The LPM marginal effects of women ’ s educatio...,0.697516,True
8,8,more_probable,The causal mechanisms by which education influ...,the heterogeneous effect of education on the p...,0.933343,True
9,9,more_probable,The impact of the one-child policy on educatio...,critical birth cohort cut-off for HE expansion...,0.843200,True
10,10,more_probable,The impact of heterogeneous exposure to higher...,the interaction effects of childhood hukou sta...,0.680694,True
11,11,more_probable,The impact of higher education expansion on ma...,our own heterogeneous effect analysis showing ...,0.685252,True
13,13,more_probable,The impact of educational attainment on marria...,Key marriage characteristics by wife ’ s birth...,0.980134,True

In [ ]:
import pandas as pd
from IPython.display import display

HC = PROJECT_ROOT / "Part3_Output" / "tabi_high_confidence_mnli06.csv"
if HC.exists():
    h = pd.read_csv(HC)
    print("===", HC.name, "===")
    print("rows:", len(h))
    cols = [c for c in ["chunk_id", "article_filename", "bucket", "mnli_entailment_prob", "claim", "grounds", "warrant"] if c in h.columns]
    display(h[cols].head(10))
else:
    print("Missing", HC, "— run: .venv/bin/python run_part3.py tabi-high-confidence --mnli-threshold 0.6 --out Part3_Output/tabi_high_confidence_mnli06.csv")

## 7. Expanded corpus (optional)

Put extra PDFs in a folder and set `GAPMAP_DATASET` **before** starting the kernel, or in cell 1:

```python
os.environ["GAPMAP_DATASET"] = "Dataset_expanded"
```

Then restart the kernel (so `run_part2` / `run_part3` pick it up) and re-run TABI cells.